# Generated by Django 4.1.1 on 2022-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingsregist',
            name='transfer_identifier',
            field=models.IntegerField(default=1),
        ),
    ]
